### ISSUE TITLE
Import assist using backslash \ not forwardslash /

### ISSUE THREAD

**Issue by johne2310** [buehler/typescript-hero#19]
Import using Windows using backslash initially then all others are forward slashes /.

E.g. import {HelloIonicPage} from './pages\hello-ionic\hello-ionic';

**Comment by buehler** [comment]
Whoops :-)
I don't work on windows, could you elaborate how it should work?
Should it be `import {HelloIonicPage} from './pages/hello-ionic/hello-ionic';`
or should it use backslashes?

**Comment by johne2310** [comment]
Hi,
Confirming it should be /
Thanks. John

On Mon, Aug 22, 2016 at 6:05 PM, Christoph Bühler <notifications@github.com> wrote:
Whoops :-)
I don't work on windows, could you elaborate how it should work?
Should it be import {HelloIonicPage} from './pages/hello-ionic/hello-ionic';
or should it use backslashes?

**Comment by buehler** [comment]
Should be fixed by #28

**Comment by johne2310** [comment]
Backslashes still showing in 0.60. See attached pic. Also additional dot at start of file string (see comparator import in pic.

![vscode typescript hero 1](https://cloud.githubusercontent.com/assets/12781989/18405130/c203132c-7732-11e6-930e-940d41885242.PNG)

**Comment by buehler** [comment]
I need to check this on a windows machine :neutral_face:
